package scanner.symbols;

public class sym {
    //Operators
    public static final int EOF = 0;            // <EOF>
    public static final int COMMA = 1;           // ","
    public static final int SEMICOLON = 2;       // ";"
    public static final int INCREMENT = 3;       // "++"
    public static final int DECREMENT = 4;       // "--"
    public static final int EQUALS = 5;          // "=="
    public static final int GREATEREQUAL = 6;    // ">="
    public static final int GREATER = 7;         // ">"
    public static final int QUESTION = 8;        // "?"
    public static final int LESSEQUAL = 9;       // "<="
    public static final int LESS = 10;           // "<"
    public static final int NOTEQUAL = 11;       // "!="
    public static final int OROR = 12;           // "||"
    public static final int ANDAND = 13;         // "&&"
    public static final int NOT = 14;            // "!"
    public static final int ASSIGN = 15;         // "="
    public static final int PLUS = 16;           // "+"
    public static final int MINUS = 17;          // "-"
    public static final int TIMES = 18;          // "*"
    public static final int DIVIDE = 19;         // "/"
    public static final int MODULO = 20;         // "%"
    public static final int LPAREN = 21;         // "("
    public static final int RPAREN = 22;         // ")"
    public static final int LBRACKET = 23;       // "["
    public static final int RBRACKET = 24;       // "]"
    public static final int LBRACE = 25;         // "{"
    public static final int RBRACE = 26;         // "}"
    public static final int COLON = 27;          // ":"
    public static final int DOT = 28;            // "."
    public static final int PLUSEQUAL = 29;      // "+="
    public static final int MINUSEQUAL = 30;     // "-="
    public static final int TIMESEQUAL = 31;     // "*="
    public static final int DIVIDEEQUAL = 32;    // "/="
    public static final int AND = 33;            // "&"
    public static final int XOR = 34;            // "^"
    public static final int OR = 35;             // "|"
    public static final int RSHIFT = 36;         // ">>"
    public static final int LSHIFT = 37;         // "<<"
    public static final int TILDE = 38;          // "~"
    public static final int MODULOEQUAL = 39;    // "%="
    public static final int ANDEQUAL = 40;       // "&="
    public static final int XOREQUAL = 41;       // "^="
    public static final int OREQUAL = 42;        // "|="
    public static final int LSHIFTEQUAL = 43;    // "<<="
    public static final int RSHIFTEQUAL = 44;    // ">>="
    public static final int ARROW = 45;          // "->"
    public static final int HASH = 46;      // "#"



    public static final int ID = 47;             // Identifier

    //Keywords
    public static final int NUM = 48;
    public static final int AUTO = 49;      // "auto"
    public static final int BREAK = 50;     // "break"
    public static final int CASE = 51;      // "case"
    public static final int CHAR = 52;      // "char"
    public static final int CONST = 53;     // "const"
    public static final int CONTINUE = 54;  // "continue"
    public static final int DEFAULT = 55;   // "default"
    public static final int DO = 56;        // "do"
    public static final int DOUBLE = 57;    // "double"
    public static final int ELSE = 58;      // "else"
    public static final int ENUM = 59;      // "enum"
    public static final int EXTERN = 60;    // "extern"
    public static final int FLOAT = 61;     // "float"
    public static final int FOR = 62;       // "for"
    public static final int GOTO = 63;      // "goto"
    public static final int IF = 64;        // "if"
    public static final int INT = 65;       // "int"
    public static final int LONG = 66;      // "long"
    public static final int REGISTER = 67;  // "register"
    public static final int RETURN = 68;    // "return"
    public static final int SHORT = 69;     // "short"
    public static final int SIGNED = 70;    // "signed"
    public static final int SIZEOF = 71;    // "sizeof"
    public static final int STATIC = 72;    // "static"
    public static final int STRUCT = 73;    // "struct"
    public static final int SWITCH = 74;    // "switch"
    public static final int TYPEDEF = 75;   // "typedef"
    public static final int UNION = 76;     // "union"
    public static final int UNSIGNED = 77;  // "unsigned"
    public static final int VOID = 78;      // "void"
    public static final int VOLATILE = 79;  // "volatile"
    public static final int WHILE = 80;     // "while"
    public static final int STRING = 81;    // "string"

}
